### ISSUE TITLE
How to use this library with a TCP connection?

### ISSUE THREAD

**Issue by asterite** [oxalica/async-lsp#12]
Hi! Sorry if this is not the right place to ask this, but how do you use this library with TCP sockets instead of stdin/stdout? I tried several variations of the code but couldn't make it compile/work. Thank you!

**Comment by oxalica** [comment]
> I tried several variations of the code but couldn't make it compile/work

What code have you tried, what error do you meet, and what's your expectation? Just saying "it does not work" does not provide any useful information.

`MainLoop::run_buffered` accepts any `Async{Read,Write}` type. You can pass async TCP streams inside it without any issue. You can check [this example](https://github.com/oxalica/async-lsp/blob/fa78d18cbd78d279f9e1d36abd7db0cbc551528e/examples/server_builder.rs#L113) for reference, and simply replacing `stdin/stdout` with the result from `tokio::net::TcpStream::split()`.

**Comment by asterite** [comment]
Thank you. Yes, I tried that split and it said it wasn't AsyncRead.

In any case I don't need this anymore so I'm going to close this.
