### ISSUE TITLE
How to tell LSP server to use UTF-8 for position encoding offsets?

### ISSUE THREAD

**Issue by Boscop** [oxalica/async-lsp#14]
How to tell LSP server to use UTF-8 for position encoding offsets?
(Assuming the LSP server is rust-analyzer. Someone told me that it now supports utf-8 for position encoding.)

I tried to test it by modifying the client_builder example, to send this after `server.initialized(InitializedParams {}).unwrap();`:
```rs
server
    .notify::<lsp_types::notification::DidChangeConfiguration>(
        lsp_types::DidChangeConfigurationParams {
            settings: serde_json::json!({
                "rust-analyzer": {
                    "experimental": {
                        "positionEncoding": "utf-8"
                    },
                },
            }),
        },
    )
    .expect("notify");
```

But it doesn't seem to work, it only shows that it supports utf-16 (RA version `0.3.2129-standalone (822644d97 2024-09-29)`):
> 2024-10-01T21:55:19.226375Z  INFO client_builder: Initialized: InitializeResult { capabilities: ServerCapabilities { position_encoding: Some(PositionEncodingKind("utf-16")), text_document_sync: Some(Options(TextDocumentSyncOptions { open_close: Some(true), change: Some(Incremental), 
[...]
server_info: Some(ServerInfo { name: "rust-analyzer", version: Some("0.3.2129-standalone (822644d97 2024-09-29)") }) }

Am I doing it wrong? 🙂

**Comment by oxalica** [comment]
The position encoding is negotiated once during initialization, not on configuration change. The client should send it via `general.positionEncodings` in [`ClientCapabilities`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#clientCapabilities) as the first initialization request to advertise the client supports it, and server will select an encoding they like as the response (can be UTF-8, if the server also supports it and wants to use).

See [Lifecycle Messages in LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#lifeCycleMessages) for how to do the initialization flow and negotiate and capabilities to use.

**Comment by Boscop** [comment]
@oxalica Thanks, I saw that lsp-types's `ClientCapabilities` type has a field for this, but it's feature-gated behind the `proposed` feature:
https://docs.rs/lsp-types/latest/src/lsp_types/lib.rs.html#1511
But this feature is not enabled when lsp-types is used as a dependency of async-lsp.
Could you please enable it or forward it via a feature of the same name? 🙂

**Comment by oxalica** [comment]
> Thanks, I saw that lsp-types's `ClientCapabilities` type has a field for this, but it's feature-gated behind the `proposed` feature:

As I mentioned, the stabilized one is at `general.positionEncodings`. If you cannot find it,  search `positionEncodings` on docs.rs. And you'll find https://docs.rs/lsp-types/0.95.0/lsp_types/struct.GeneralClientCapabilities.html#structfield.position_encodings

Some server may require additional secret options to be set in order to enable this support. I have not checked rust-analyzer requires any. You need to check their docs for details. I don't think it's related to async-lsp.

**Comment by Boscop** [comment]
Thanks so much, it works now 😊
