### ISSUE TITLE
Not getting semantic_tokens requests for custom language

### ISSUE THREAD

**Issue by TheLazyDutchman** [oxalica/async-lsp#17]
First of all, thank you very much for making this library.

I frankly doubt that this issue would be caused by a bug in this library, but after searching extensively on the internet I could find nothing else that might cause it so I thought I would pose it here where people have more experience with writing language servers.

With that out of the way, this is the first time I tried making a language server for a custom language, and at first I was just trying some stuff out.

The problem is the following:
When I open a test file with the `.scaffold` extension, I expect the first token to be colored, but that is not the case.

I have tested the following:
- `:LspInfo` => My language server is running and connected to the buffer
- Other actions => both `Goto definition` and `Code action` return the expected default result from the language server
- `:Inspect` => this vim command should return the data that `semantic_tokens` returned for the token under the cursor, when I tried this in a rust file it returned the expected data, so vim does send the `semantic_tokens` request to `rust_analyzer` and my colorscheme does not break it. However, when I tried it in the `.scaffold` file at the location that the default function should report a token, neovim says that there is no token there.

So, here is the `initialize` function and `semantic_tokens` functions:
```rust
impl LanguageServer for ServerState {
	type Error = ResponseError;
	type NotifyResult = ControlFlow<async_lsp::Result<()>>;

	fn initialize(
		&mut self,
		params: InitializeParams,
	) -> BoxFuture<'static, Result<InitializeResult, Self::Error>> {
		eprintln!(
			"Initialize with {:?}",
			params
				.capabilities
				.text_document
				.unwrap()
				.semantic_tokens
				.unwrap()
				.token_types
		);
		Box::pin(async move {
			Ok(InitializeResult {
				capabilities: ServerCapabilities {
					position_encoding: Some(PositionEncodingKind::UTF8),
					hover_provider: Some(HoverProviderCapability::Simple(true)),

					definition_provider: Some(OneOf::Left(true)),
					semantic_tokens_provider: Some(
						SemanticTokensServerCapabilities::SemanticTokensOptions(
							SemanticTokensOptions {
								work_done_progress_options: WorkDoneProgressOptions::default(),
								legend: SemanticTokensLegend {
									token_types: vec![SemanticTokenType::FUNCTION],
									token_modifiers: vec![SemanticTokenModifier::DEFAULT_LIBRARY],
								},
								range: Some(true),
								full: Some(SemanticTokensFullOptions::Delta { delta: Some(true) }),
							},
						),
					),
					code_action_provider: Some(CodeActionProviderCapability::Options(
						CodeActionOptions {
							code_action_kinds: Some(vec![CodeActionKind::new("refactor")]),
							work_done_progress_options: WorkDoneProgressOptions::default(),
							resolve_provider: None,
						},
					)),
					..ServerCapabilities::default()
				},
				server_info: None,
			})
		})
	}

	// Some other functions with default implementations

	fn semantic_tokens_full(
		&mut self,
		_: SemanticTokensParams,
	) -> BoxFuture<'static, Result<Option<SemanticTokensResult>, ResponseError>> {
		Box::pin(async move {
			Ok(Some(SemanticTokensResult::Tokens(SemanticTokens {
				result_id: None,
				data: vec![SemanticToken {
					delta_line: 0,
					delta_start: 0,
					length: 5,
					token_modifiers_bitset: 0,
					token_type: 0,
				}],
			})))
		})
	}

	fn semantic_tokens_full_delta(
		&mut self,
		_: SemanticTokensDeltaParams,
	) -> BoxFuture<'static, Result<Option<SemanticTokensFullDeltaResult>, ResponseError>> {
		Box::pin(async move {
			Ok(Some(SemanticTokensFullDeltaResult::Tokens(
				SemanticTokens {
					result_id: None,
					data: vec![SemanticToken {
						delta_line: 0,
						delta_start: 0,
						length: 5,
						token_modifiers_bitset: 0,
						token_type: 0,
					}],
				},
			)))
		})
	}

	fn semantic_tokens_range(
		&mut self,
		_: SemanticTokensRangeParams,
	) -> BoxFuture<'static, Result<Option<SemanticTokensRangeResult>, ResponseError>> {
		Box::pin(async move {
			Ok(Some(SemanticTokensRangeResult::Tokens(SemanticTokens {
				result_id: None,
				data: vec![SemanticToken {
					delta_line: 0,
					delta_start: 0,
					length: 5,
					token_modifiers_bitset: 0,
					token_type: 0,
				}],
			})))
		})
	}
}
```

And this is the code that starts my language server in vim:
```lua
local lspconfig = require 'lspconfig'
local configs = require 'lspconfig.configs'

if not configs.scaffold_analyzer then
  configs.scaffold_analyzer = {
    default_config = {
      cmd = { '/home/hummingphoenix/Desktop/projects/scaffold/scaffold_analyzer/target/release/scaffold_analyzer' },
      root_dir = lspconfig.util.root_pattern('.git'),
      filetypes = { 'scaffold' },
    },
  }
end
lspconfig.scaffold_analyzer.setup {}
```

And the code that adds `scaffold` as a language
```lua
vim.filetype.add({
	extension = {
		scaffold = "scaffold"
	}
})
```

I know that this might not be the best place to ask, but I hope that you can still help me, or otherwise point me in a direction where I might find the answer myself, because I am out of my wits.

**Comment by oxalica** [comment]
> The problem is the following:
> When I open a test file with the `.scaffold` extension, I expect the first token to be colored, but that is not the case.

This is quite a vague description. How do you know the "something wrong" is caused by this library, not your editor or editor plugin? Also that you said you are using vim, but also giving lua script and `lspconfig` plugin, which are all neovim specific stuff, not vim at all.

For general guide, I suggest to debug your program with your LSP client setup, to check if `semantic_tokens_*` is called at all, via `eprintln!` or logs. And also check the stderr log of your server (check the manual of your editor and/or plugin to learn how to).
- If it is not called, then it's probably a negotiation issue, possibly because your editor/plugin does not support it.
- If it is called but the token is not rendered, then check if your color theme plugin has the highlight definition for the semantic token type `FUNCTION` (in the manual of your color scheme plugin). I don't think vim has a default highlighting for it, but not sure whether neovim has a default one.

If you are sure it's an library issue, please give the minimal reproduction code and relevant LSP messages. This is unlikely the case because it works for my LSP server on my editor setup.

**Comment by TheLazyDutchman** [comment]
Thank you for your help. After some more testing I managed to get it working. It seems like neovim does not send the `semantic_tokens_*` request if the server does not support the `text_document_sync` capability even if it does support semantic tokens.
