### ISSUE TITLE
Need a way to construct a ClientSocket

### ISSUE THREAD

**Issue by phated** [oxalica/async-lsp#2]
I'd like to implement unit tests that take my server state and params and I'll assert on the response; however, if I add the ClientSocket to my state, I don't have a way to create it without `Frontend::new(builder)`. Ideally, the ClientSocket and ServerSocket would have constructor functions to build one up for unit testing, etc.

**Comment by phated** [comment]
I was hoping to create unit tests that didn't care what was sent on the channel, so only the return value is asserted. I can write a wrapper around the ClientSocket that stubs it on unit tests, but that seemed like overkill.

**Comment by oxalica** [comment]
> so only the return value is asserted

It is what I did in the test example link above.

> I can write a wrapper around the ClientSocket that stubs it on unit tests

I did not get it. If you can construct `*Socket`, how do you utilize it in tests? Could you give some example codes about what you want to write?

**Comment by phated** [comment]
> If you can construct *Socket, how do you utilize it in tests?

I don't plan to utilize the Socket types in the tests, but they must be present to construct a state struct. If the ClientSocket is just being used for `show_message`, then those don't need to be tested, imo.

> Could you give some example codes about what you want to write?

I want the tests to look like https://github.com/noir-lang/noir/blob/phated/lsp-scaffold/crates/lsp/src/lib.rs#L155-L162 even when I add the `ClientSocket` to the state struct. Other than the test (which can be conditionally swapped with wasm-bindgen-test), the crate doesn't have any unix/tokio features enabled, since it is platform agnostic and needs to compile to wasm32 architecture.

Without being able to construct a no-op ClientSocket, I'll need to create an abstraction on top of it (similar to your `ClientExt::show_message_ext` in nil) which would allow a stubbed `show_message` API for tests.

**Comment by oxalica** [comment]
> I don't plan to utilize the Socket types in the tests, but they must be present to construct a state struct. If the ClientSocket is just being used for `show_message`, then those don't need to be tested, imo.

Fair enough. I added null constructors in abd0877c4ec2a3362ce4c906b77d48150843711d.
