### ISSUE TITLE
Implementing the LspService trait doesn't allow custom errors

### ISSUE THREAD

**Issue by phated** [oxalica/async-lsp#3]
I implemented the LspService trait on my own struct that wraps a router, but if I try to change the `type Error` in the `Service<AnyRequest>` trait, the types don't seem to match up. I believe this is because the LspService trait always forces the `ResponseError` type on the Service trait (`Service<AnyRequest, Response = JsonValue, Error = ResponseError>`)

**Comment by oxalica** [comment]
Rust does not yet stabilize `trait LspService: Service<.., Error: From<ResponseError> + Into<ResponseError>>`, and using where clause does not work either (https://github.com/rust-lang/rust/issues/111926). We could alternatively add these bounds to every `LspService` usages, but that would be too tedious.

Not sure if there is a better way to implement is.
