### ISSUE TITLE
`ServerSocket.document_symbol` always interprets empty list as Flat

### ISSUE THREAD

**Issue by tonyxty** [oxalica/async-lsp#7]
It is slightly annoying to handle both cases when the server is known to always return a `Nested` structure.  Can you provide an option so that the empty list will be returned as `Nested([])` instead?

**Comment by oxalica** [comment]
The standard response type is defined by [`DocumentSymbolResponse` in `lsp-types` crate](https://docs.rs/lsp-types/0.95.0/lsp_types/enum.DocumentSymbolResponse.html). `async-lsp` follows it without post-processing.

If you want to add non-standard requests or notifications, you can define custom request and response types via [`trait Request`](https://docs.rs/lsp-types/0.95.0/lsp_types/request/trait.Request.html), and register corresponding handlers via [`Router::request`](https://docs.rs/async-lsp/0.1.0/async_lsp/router/struct.Router.html#method.request).
