### ISSUE TITLE
Compiling to `wasm32-wasi` target

### ISSUE THREAD

**Issue by micahscopes** [oxalica/async-lsp#8]
I was able to get the server trait example to compile to `wasm32-wasi` with a few considerations:

- It's necessary to disable unsupported features from both `async-lsp` and `tokio`, specifically `tokio/io-std` and `async-lsp/client-monitor`:
```
[target.'cfg(target_arch = "wasm32")'.dependencies]
async-lsp = { version = "0.2.0", default-features = false, features = ["omni-trait", "stdio", "tracing"] }
tokio = { version = "1.35.1", default-features = false, features = ["sync", "macros", "io-util", "rt", "time"] }
```
- I also needed to limit use of any `async-std` dependency to non-wasm targets:
```
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "1.12.0"
```

I made dummy `AsyncRead` and `AsyncWrite` just to get it to compile but haven't actually hooked up anything useful.  My usecase is to eventually run the language server in the browser and I wanted to make sure I could get `async-lsp` to compile to WASI for use with something like [wasmer-js](https://wasmer.io/posts/introducing-the-wasmer-js-sdk).

I'm not sure if it's worth documenting this in the readme, but I at least wanted to make this issue in case anyone else is trying this.

**Comment by oxalica** [comment]
Thanks for the test. 

> * It's necessary to disable unsupported features from both `async-lsp` and `tokio`, specifically `tokio/io-std`

I think `tokio/io-std` *should be able to* support WASI, but it's up to them and is not actionable here.

>  and `async-lsp/client-monitor`

[`waitpid-any`](https://github.com/oxalica/waitpid-any) does not and will not support WASI, since relevant syscalls are missing. So this is intended.

Are you expecting these features being removed from the default feature set?


> * I also needed to limit use of any `async-std` dependency to non-wasm targets:
> I made dummy `AsyncRead` and `AsyncWrite` just to get it to compile but haven't actually hooked up anything useful.


We currently does not depend on `async-std`. Only `futures::Async{Read,Write}` interfaces are used under `stdio` feature. I don't think there is any compatibility issue about this.

> I'm not sure if it's worth documenting this in the readme

PRs are welcome.

**Comment by wiiznokes** [comment]
Wanted to give this idea a shot too. I initially compiled succefully `lsp-server` to wasm but this crate seems way better. I wonder if spawning the server in a [worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) is feasible/a good idea.

**Comment by micahscopes** [comment]
> Are you expecting these features being removed from the default feature set?

@oxalica not necessarily, though that might not be a bad idea. Mostly I just wanted to document this so that others who are interested in the WASI target don't have put as much effort in.

> I wonder if spawning the server in a worker is feasible/a good idea.

You might be interested in [@wasmer/ask](https://wasmer.io/posts/introducing-the-wasmer-js-sdk). I still haven't figured out how to properly set up IO in the WASI build but I don't see anything preventing that. I guess you could make `AsyncRead` and `AsyncWrite` adapters for the WASI io interface. I haven't found a crate for that yet though or dug into how to do that. Otherwise maybe you could make async adapters for a `MesaageChannel` passed to the worker?

**Comment by oxalica** [comment]
Close as no actions needed. It should already work with default features disabled.
